/**
 * ai-ui.js
 * Handles the display of AI analysis reports.
 */

window.runAIAnalysis = function(wellId) {
    console.log("Requesting AI Analysis for:", wellId);
    
    // Find well data
    const well = mockData.rigs.find(r => r.id === wellId);
    if (!well) {
        alert("Well data not found locally.");
        return;
    }

    // Run Analysis
    const result = wellAnalyst.analyze(well);
    
    // Show Modal
    showAIModal(result, well.name);
};

function showAIModal(report, wellName) {
    // Remove existing modal
    const existing = document.getElementById('ai-modal');
    if (existing) existing.remove();

    const scoreColor = report.score >= 80 ? '#00b894' : report.score >= 50 ? '#fdcb6e' : '#d63031';

    const modalHTML = `
        <div id="ai-modal" style="position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.8); z-index: 10000; display: flex; align-items: center; justify-content: center; backdrop-filter: blur(5px);">
            <div style="background: #1e272e; width: 90%; max-width: 600px; border-radius: 16px; overflow: hidden; box-shadow: 0 10px 30px rgba(0,0,0,0.5); border: 1px solid #485460; font-family: 'Outfit', sans-serif;">
                
                <!-- Header -->
                <div style="background: linear-gradient(135deg, #6c5ce7, #a29bfe); padding: 20px; display: flex; justify-content: space-between; align-items: center;">
                    <h2 style="margin: 0; color: white; display: flex; align-items: center; gap: 10px;">
                        <i class="fa-solid fa-robot fa-bounce"></i> GeoWell AI Analyst
                    </h2>
                    <button onclick="document.getElementById('ai-modal').remove()" style="background: none; border: none; color: white; font-size: 20px; cursor: pointer;">
                        <i class="fa-solid fa-xmark"></i>
                    </button>
                </div>

                <!-- Body -->
                <div style="padding: 25px; color: #dcdde1; max-height: 70vh; overflow-y: auto;">
                    
                    <!-- Score & Summary -->
                    <div style="display: flex; align-items: center; gap: 20px; margin-bottom: 25px; background: rgba(255,255,255,0.05); padding: 15px; border-radius: 12px;">
                        <div style="position: relative; width: 80px; height: 80px; display: flex; align-items: center; justify-content: center; border-radius: 50%; border: 6px solid ${scoreColor}; font-size: 24px; font-weight: bold; color: white;">
                            ${report.score}
                        </div>
                        <div>
                            <h3 style="margin: 0 0 5px 0; color: white;">${wellName}</h3>
                            <div style="font-size: 14px; color: #b2bec3;">${report.summary}</div>
                        </div>
                    </div>

                    <!-- Alerts -->
                    ${report.alerts.length > 0 ? `
                        <h4 style="color: #ff7675; margin-bottom: 10px; display: flex; align-items: center; gap: 8px;">
                            <i class="fa-solid fa-triangle-exclamation"></i> Detected Issues
                        </h4>
                        <div style="display: flex; flex-direction: column; gap: 10px; margin-bottom: 25px;">
                            ${report.alerts.map(alert => `
                                <div style="background: rgba(214, 48, 49, 0.15); border-left: 4px solid ${alert.type === 'critical' ? '#d63031' : '#fdcb6e'}; padding: 12px; border-radius: 4px; font-size: 13px;">
                                    <strong>${alert.message}</strong>
                                </div>
                            `).join('')}
                        </div>
                    ` : ''}

                    <!-- Recommendations -->
                    ${report.recommendations.length > 0 ? `
                        <h4 style="color: #55efc4; margin-bottom: 10px; display: flex; align-items: center; gap: 8px;">
                            <i class="fa-solid fa-clipboard-check"></i> Recommendations
                        </h4>
                        <ul style="background: rgba(85, 239, 196, 0.1); padding: 15px 15px 15px 35px; border-radius: 8px; font-size: 14px; margin: 0;">
                            ${report.recommendations.map(rec => `<li style="margin-bottom: 5px;">${rec}</li>`).join('')}
                        </ul>
                    ` : ''}

                </div>

                <!-- Footer -->
                <div style="padding: 15px; background: #0b0e11; text-align: center; font-size: 12px; color: #636e72;">
                    Analysis generated by GeoWell algorithms based on real-time sensor data.
                </div>
            </div>
        </div>
    `;

    document.body.insertAdjacentHTML('beforeend', modalHTML);
}
